In [1]:
import numpy as np
import glob

def loadVelodynePoints(directory):
    arr = []
    
    # Check if the last charact of the given directory is /, if not, append it.
    if (directory[-1] != '/'):
        directory += '/' 
    
    # Load all binary files in order.
    for file in sorted(glob.glob( (directory + '*.bin') )):
        arr.append(np.fromfile(file, dtype=np.float16)) # Loading with float16(half precision) than float32 reduces the ram usage a lot.
        
    return arr

In [2]:
data = loadVelodynePoints('./data/velodyne_points/')

In [12]:
data

[array([ 1.104  ,  3.021  , -0.01531, ..., -1.966  ,  0.     ,  0.     ],
       dtype=float16),
 array([ 5.450e+02,  3.020e+00, -3.242e-04, ..., -1.966e+00,  0.000e+00,
         0.000e+00], dtype=float16),
 array([-1.562e-05,  3.018e+00,  6.680e-01, ..., -1.967e+00,  0.000e+00,
         0.000e+00], dtype=float16),
 array([ 4.628e+02,  3.016e+00, -4.685e-05, ..., -1.967e+00,  0.000e+00,
         0.000e+00], dtype=float16),
 array([ 3.958e+04,  3.014e+00,  1.594e-03, ..., -1.967e+00,  0.000e+00,
         0.000e+00], dtype=float16),
 array([ 9.504e+03,  3.012e+00,  3.958e+04, ..., -1.967e+00,  0.000e+00,
         0.000e+00], dtype=float16),
 array([-6.253e-05,  3.010e+00, -6.474e+04, ..., -1.968e+00,  0.000e+00,
         0.000e+00], dtype=float16),
 array([-1.591e-04,  3.008e+00,  3.972e+02, ..., -1.969e+00,  0.000e+00,
         0.000e+00], dtype=float16),
 array([-1.531e-02,  3.006e+00, -1.629e+02, ..., -1.968e+00,  0.000e+00,
         0.000e+00], dtype=float16),
 array([ 1.930e-01,  3.

---